package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.26 18:34:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class NimetTest {



  // Generated by ComTest BEGIN
  /** testLisaa44 */
  @Test
  public void testLisaa44() {    // Nimet: 44
    Nimet koe = new Nimet(); 
    Nimi n3 = new Nimi(3, "Kolmas"); 
    Nimi n1 = new Nimi(1, "eka"); 
    Nimi n2 = new Nimi(2, "toinen"); 
    assertEquals("From: Nimet line: 49", 0, koe.getlkm()); 
    koe.lisaa(n1); 
    koe.lisaa(n3); 
    assertEquals("From: Nimet line: 52", 2, koe.getlkm()); 
    koe.lisaa(n2); 
    assertEquals("From: Nimet line: 54", 3, koe.getlkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnna79 
   * @throws IndexOutOfBoundsException when error
   */
  @Test
  public void testAnna79() throws IndexOutOfBoundsException {    // Nimet: 79
    Nimet koe = new Nimet(); 
    Nimi n3 = new Nimi(3, "Kolmas"); 
    Nimi n1 = new Nimi(1, "eka"); 
    Nimi n2 = new Nimi(2, "toinen"); 
    koe.lisaa(n1); 
    try {
    assertEquals("From: Nimet line: 86", null, koe.anna(1)); 
    fail("Nimet: 86 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    koe.lisaa(n3); 
    koe.lisaa(n2); 
    assertEquals("From: Nimet line: 89", "1|eka", koe.anna(0).toString()); 
    assertEquals("From: Nimet line: 90", "3|Kolmas", koe.anna(1).toString()); 
    assertEquals("From: Nimet line: 91", "2|toinen", koe.anna(2).toString()); 
    try {
    assertEquals("From: Nimet line: 92", null, koe.anna(3)); 
    fail("Nimet: 92 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsiNimi105 */
  @Test
  public void testEtsiNimi105() {    // Nimet: 105
    Nimet koe = new Nimet(); 
    Nimi n3 = new Nimi(3, "Kolmas"); 
    Nimi n1 = new Nimi(1, "eka"); 
    Nimi n2 = new Nimi(2, "toinen"); 
    koe.lisaa(n1); 
    koe.lisaa(n3); 
    koe.lisaa(n2); 
    assertEquals("From: Nimet line: 113", "1|eka", koe.etsiNimi(1).toString()); 
    assertEquals("From: Nimet line: 114", "3|Kolmas", koe.etsiNimi(3).toString()); 
    assertEquals("From: Nimet line: 115", "2|toinen", koe.etsiNimi(2).toString()); 
    assertEquals("From: Nimet line: 116", null, koe.etsiNimi(0)); 
  } // Generated by ComTest END
}