package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.31 13:55:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class NimiTest {



  // Generated by ComTest BEGIN
  /** testNimi17 */
  @Test
  public void testNimi17() {    // Nimi: 17
    Nimi n; 
    n = new Nimi(1,"ABC"); assertEquals("From: Nimi line: 24", "1|ABC", n.toString());  
    n = new Nimi(3,"12\n3"); assertEquals("From: Nimi line: 25", "3|12\n3", n.toString());  
    n = new Nimi(1,""); assertEquals("From: Nimi line: 26", "1|", n.toString());  
    ; assertEquals("From: Nimi line: 27", "1|", n.toString());  
    n = new Nimi(15,"Perus"); assertEquals("From: Nimi line: 28", "15|Perus", n.toString());  
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi46 */
  @Test
  public void testGetNimi46() {    // Nimi: 46
    Nimi n; 
    n = new Nimi(1,"ABC"); assertEquals("From: Nimi line: 53", "ABC", n.getNimi());  
    n = new Nimi(3,"12\n3"); assertEquals("From: Nimi line: 54", "12\n3", n.getNimi());  
    n = new Nimi(1,""); assertEquals("From: Nimi line: 55", "", n.getNimi());  
    ; assertEquals("From: Nimi line: 56", "", n.getNimi());  
    n = new Nimi(15,"Perus"); assertEquals("From: Nimi line: 57", "Perus", n.getNimi());  
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetRataId68 */
  @Test
  public void testGetRataId68() {    // Nimi: 68
    Nimi n; 
    n = new Nimi(1,"ABC"); assertEquals("From: Nimi line: 75", 1, n.getRataId());  
    n = new Nimi(3,"12\n3"); assertEquals("From: Nimi line: 76", 3, n.getRataId());  
    n = new Nimi(1,""); assertEquals("From: Nimi line: 77", 1, n.getRataId());  
    ; assertEquals("From: Nimi line: 78", 1, n.getRataId());  
    n = new Nimi(15,"Perus"); assertEquals("From: Nimi line: 79", 15, n.getRataId());  
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testParse97 
   * @throws NumberFormatException when error
   */
  @Test
  public void testParse97() throws NumberFormatException {    // Nimi: 97
    Nimi koe = new Nimi(); 
    koe.parse("1 | koe"); 
    assertEquals("From: Nimi line: 101", "1|koe", koe.toString());
    koe.parse("      2 \n\n | \n             riviKoe \n"); 
    assertEquals("From: Nimi line: 103", "2|riviKoe", koe.toString()); 
    try {
    koe.parse(" | "); 
    fail("Nimi: 104 Did not throw NumberFormatException");
    } catch(NumberFormatException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}