package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.24 22:02:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class NimiTest {



  // Generated by ComTest BEGIN
  /** testNimi17 */
  @Test
  public void testNimi17() {    // Nimi: 17
    Nimi n; 
    n = new Nimi(1,"ABC"); assertEquals("From: Nimi line: 24", "1|ABC", n.toString());  
    n = new Nimi(3,"12\n3"); assertEquals("From: Nimi line: 25", "3|12\n3", n.toString());  
    n = new Nimi(1,""); assertEquals("From: Nimi line: 26", "1|", n.toString());  
    ; assertEquals("From: Nimi line: 27", "1|", n.toString());  
    n = new Nimi(15,"Perus"); assertEquals("From: Nimi line: 28", "15|Perus", n.toString());  
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi40 */
  @Test
  public void testGetNimi40() {    // Nimi: 40
    Nimi n; 
    n = new Nimi(1,"ABC"); assertEquals("From: Nimi line: 47", "ABC", n.getNimi());  
    n = new Nimi(3,"12\n3"); assertEquals("From: Nimi line: 48", "12\n3", n.getNimi());  
    n = new Nimi(1,""); assertEquals("From: Nimi line: 49", "", n.getNimi());  
    ; assertEquals("From: Nimi line: 50", "", n.getNimi());  
    n = new Nimi(15,"Perus"); assertEquals("From: Nimi line: 51", "Perus", n.getNimi());  
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetRataId62 */
  @Test
  public void testGetRataId62() {    // Nimi: 62
    Nimi n; 
    n = new Nimi(1,"ABC"); assertEquals("From: Nimi line: 69", 1, n.getRataId());  
    n = new Nimi(3,"12\n3"); assertEquals("From: Nimi line: 70", 3, n.getRataId());  
    n = new Nimi(1,""); assertEquals("From: Nimi line: 71", 1, n.getRataId());  
    ; assertEquals("From: Nimi line: 72", 1, n.getRataId());  
    n = new Nimi(15,"Perus"); assertEquals("From: Nimi line: 73", 15, n.getRataId());  
  } // Generated by ComTest END
}