package tuloskortti.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.24 21:47:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ParitTest {



  // Generated by ComTest BEGIN
  /** testGetlkm44 */
  @Test
  public void testGetlkm44() {    // Parit: 44
    Parit koe2 = new Parit(); 
    Par f = new Par(9, 6, 6); 
    Par c = new Par(9, 3, 3); 
    Par d = new Par(9, 4, 4); 
    Par a = new Par(9, 1, 1); 
    Par e = new Par(9, 5, 5); 
    Par b = new Par(9, 2, 2); 
    koe2.lisaa(b); 
    koe2.lisaa(e); 
    assertEquals("From: Parit line: 56", 2, koe2.getlkm()); 
    koe2.lisaa(c); 
    koe2.lisaa(d); 
    koe2.lisaa(a); 
    koe2.lisaa(f); 
    assertEquals("From: Parit line: 61", 6, koe2.getlkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetRadanParluvut73 */
  @Test
  public void testGetRadanParluvut73() {    // Parit: 73
    Parit koe2 = new Parit(); 
    Par f = new Par(9, 6, 6); 
    Par c = new Par(9, 3, 3); 
    Par d = new Par(9, 4, 4); 
    Par a = new Par(9, 1, 1); 
    Par e = new Par(9, 5, 5); 
    Par b = new Par(9, 2, 2); 
    koe2.lisaa(b); 
    koe2.lisaa(e); 
    koe2.lisaa(c); 
    koe2.lisaa(d); 
    koe2.lisaa(a); 
    koe2.lisaa(f); 
    int[] koeLuku = new int[18]; 
    koeLuku = koe2.getRadanParluvut(9); 
    assertEquals("From: Parit line: 91", "[1, 2, 3, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]", Arrays.toString(koeLuku)); 
  } // Generated by ComTest END
}