package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.23 16:55:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ParTest {



  // Generated by ComTest BEGIN
  /** testGetRataId29 */
  @Test
  public void testGetRataId29() {    // Par: 29
    Par koe = new Par(0,1,3); 
    assertEquals("From: Par line: 31", 0, koe.getRataId()); 
    Par koe2 = new Par(0,2,4); 
    assertEquals("From: Par line: 33", 0, koe2.getRataId()); 
    Par koe3 = new Par(500,-1,0); 
    assertEquals("From: Par line: 35", 500, koe3.getRataId()); 
    Par koe4 = new Par(0,0,0); 
    assertEquals("From: Par line: 37", 0, koe4.getRataId()); 
    Par koe5 = new Par(1,20,3); 
    assertEquals("From: Par line: 39", 1, koe5.getRataId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetVayla49 */
  @Test
  public void testGetVayla49() {    // Par: 49
    Par koe = new Par(0,1,3); 
    assertEquals("From: Par line: 51", 1, koe.getVayla()); 
    Par koe2 = new Par(0,2,4); 
    assertEquals("From: Par line: 53", 2, koe2.getVayla()); 
    Par koe3 = new Par(500,-1,0); 
    assertEquals("From: Par line: 55", -1, koe3.getVayla()); 
    Par koe4 = new Par(0,0,0); 
    assertEquals("From: Par line: 57", 0, koe4.getVayla()); 
    Par koe5 = new Par(1,20,3); 
    assertEquals("From: Par line: 59", 20, koe5.getVayla()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPar69 */
  @Test
  public void testGetPar69() {    // Par: 69
    Par koe = new Par(0,1,3); 
    assertEquals("From: Par line: 71", 3, koe.getPar()); 
    Par koe2 = new Par(0,2,4); 
    assertEquals("From: Par line: 73", 4, koe2.getPar()); 
    Par koe3 = new Par(500,-1,0); 
    assertEquals("From: Par line: 75", 0, koe3.getPar()); 
    Par koe4 = new Par(0,0,0); 
    assertEquals("From: Par line: 77", 0, koe4.getPar()); 
    Par koe5 = new Par(1,20,3); 
    assertEquals("From: Par line: 79", 3, koe5.getPar()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString88 */
  @Test
  public void testToString88() {    // Par: 88
    Par koe = new Par(0,1,3); 
    assertEquals("From: Par line: 90", "0|1|3", koe.toString()); 
    Par koe2 = new Par(0,2,4); 
    assertEquals("From: Par line: 92", "0|2|4", koe2.toString()); 
    Par koe3 = new Par(500,-1,0); 
    assertEquals("From: Par line: 94", "500|-1|0", koe3.toString()); 
    Par koe4 = new Par(0,0,0); 
    assertEquals("From: Par line: 96", "0|0|0", koe4.toString()); 
    Par koe5 = new Par(1,20,3); 
    assertEquals("From: Par line: 98", "1|20|3", koe5.toString()); 
  } // Generated by ComTest END
}