package tuloskortti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.23 13:26:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RataTietoTest {



  // Generated by ComTest BEGIN
  /** testToString110 */
  @Test
  public void testToString110() {    // RataTieto: 110
    int[] koePar = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} ; 
    RataTieto rata1 = new RataTieto(1, "rata1" , koePar); 
    int[] koePar2 = { 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3} ; 
    RataTieto rata2 = new RataTieto(2, "rata2", koePar2); 
    int[] koePar3 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1} ; 
    RataTieto rata3 = new RataTieto(1, "rata3", koePar3); 
    RataTieto rata4 = new RataTieto(); 
    assertEquals("From: RataTieto line: 118", "1|rata1|1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18", rata1.toString()); 
    assertEquals("From: RataTieto line: 119", "2|rata2|3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3", rata2.toString()); 
    assertEquals("From: RataTieto line: 120", "1|rata3|1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1", rata3.toString()); 
    assertEquals("From: RataTieto line: 121", "0|null|0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0", rata4.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone137 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone137() throws CloneNotSupportedException {    // RataTieto: 137
    int[] koePar = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} ; 
    RataTieto rata1 = new RataTieto(1, "rata1" , koePar); 
    assertEquals("From: RataTieto line: 142", "1|rata1|1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18", rata1.toString()); 
    RataTieto rata2 = (RataTieto)rata1.clone(); 
    assertEquals("From: RataTieto line: 144", "1|rata1|1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18", rata2.toString()); 
    rata1.setNimi("Muutettu"); 
    assertEquals("From: RataTieto line: 146", "1|Muutettu|1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18", rata1.toString()); 
    assertEquals("From: RataTieto line: 147", "1|rata1|1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18", rata2.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAseta176 
   * @throws NumberFormatException when error
   */
  @Test
  public void testAseta176() throws NumberFormatException {    // RataTieto: 176
    int[] koePar = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} ; 
    RataTieto rata1 = new RataTieto(1, "rata1" , koePar); 
    assertEquals("From: RataTieto line: 181", null, rata1.aseta(0, "Ensimmäinen")); 
    assertEquals("From: RataTieto line: 182", null, rata1.aseta(18, "100")); 
    assertEquals("From: RataTieto line: 183", "Radalla täytyy olla nimi!", rata1.aseta(0, "")); 
    assertEquals("From: RataTieto line: 184", "Par voi olla vain numero!", rata1.aseta(2, "a")); 
    assertEquals("From: RataTieto line: 185", "Asetus epäonnistui", rata1.aseta(20, "4")); 
    assertEquals("From: RataTieto line: 186", "1|Ensimmäinen|1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 100", rata1.toString()); 
  } // Generated by ComTest END
}