package tuloskortti.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.22 22:01:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RataTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi46 */
  @Test
  public void testRekisteroi46() {    // Rata: 46
    Rata koe = new Rata(1); 
    assertEquals("From: Rata line: 48", 0, koe.uusinId()); 
    koe.rekisteroi(); 
    assertEquals("From: Rata line: 50", 1, koe.uusinId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaRata64 */
  @Test
  public void testLisaaRata64() {    // Rata: 64
    Rata lisakoe = new Rata(1); 
    int[] koePar = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} ; 
    RataTieto rata1 = new RataTieto(1, "rata1" , koePar); 
    int[] koePar2 = { 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3} ; 
    RataTieto rata2 = new RataTieto(2, "rata2", koePar2); 
    int[] koePar3 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1} ; 
    RataTieto rata3 = new RataTieto(1, "rata3", koePar3); 
    lisakoe.lisaaRata(rata1); 
    assertEquals("From: Rata line: 75", 1, lisakoe.annaRataMaara()); 
    lisakoe.lisaaRata(rata2); 
    lisakoe.lisaaRata(rata3); 
    assertEquals("From: Rata line: 78", 3, lisakoe.annaRataMaara()); 
    assertEquals("From: Rata line: 79", 3, lisakoe.uusinId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKorvaaRata104 */
  @Test
  public void testKorvaaRata104() {    // Rata: 104
    Rata kkoe = new Rata(1); 
    int[] koePar = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} ; 
    RataTieto rata1 = new RataTieto(1, "rata1" , koePar); 
    int[] koePar2 = { 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3} ; 
    RataTieto rata2 = new RataTieto(1, "rata2", koePar2); 
    int[] koePar3 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1} ; 
    RataTieto rata3 = new RataTieto(1, "rata3", koePar3); 
    kkoe.lisaaRata(rata1); 
    kkoe.lisaaRata(rata2); 
    assertEquals("From: Rata line: 116", "1|rata1|1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18", kkoe.kasaaRata(1).toString()); 
    assertEquals("From: Rata line: 117", "2|rata2|3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3", kkoe.kasaaRata(2).toString()); 
    kkoe.korvaaRata(rata3); 
    assertEquals("From: Rata line: 119", "1|rata3|1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1", kkoe.kasaaRata(1).toString()); 
    assertEquals("From: Rata line: 120", "2|rata2|3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3", kkoe.kasaaRata(2).toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKasaaRata146 */
  @Test
  public void testKasaaRata146() {    // Rata: 146
    Rata kasakoe = new Rata(1); 
    int[] koePar = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} ; 
    RataTieto rata1 = new RataTieto(1, "rata1" , koePar); 
    int[] koePar2 = { 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3} ; 
    RataTieto rata2 = new RataTieto(2, "rata2", koePar2); 
    int[] koePar3 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1} ; 
    RataTieto rata3 = new RataTieto(1, "rata3", koePar3); 
    kasakoe.lisaaRata(rata1); 
    kasakoe.lisaaRata(rata2); 
    kasakoe.lisaaRata(rata3); 
    assertEquals("From: Rata line: 159", "1|rata1|1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18", kasakoe.kasaaRata(1).toString()); 
    assertEquals("From: Rata line: 160", "3|rata3|1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1", kasakoe.kasaaRata(3).toString()); 
    assertEquals("From: Rata line: 161", null, kasakoe.kasaaRata(4)); 
    assertEquals("From: Rata line: 162", null, kasakoe.kasaaRata(-1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaRataMaara186 */
  @Test
  public void testAnnaRataMaara186() {    // Rata: 186
    Rata koe = new Rata(1); 
    assertEquals("From: Rata line: 188", 0, koe.annaRataMaara()); 
    koe.perusRata(); 
    assertEquals("From: Rata line: 190", 1, koe.annaRataMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testUusinId202 */
  @Test
  public void testUusinId202() {    // Rata: 202
    Rata koe = new Rata(1); 
    assertEquals("From: Rata line: 204", 0, koe.uusinId()); 
    koe.rekisteroi(); 
    assertEquals("From: Rata line: 206", 1, koe.uusinId()); 
    koe.perusRata(); 
    assertEquals("From: Rata line: 208", 2, koe.uusinId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsiRadat220 */
  @Test
  public void testEtsiRadat220() {    // Rata: 220
    Rata hakukoe = new Rata(1); 
    int[] koePar = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} ; 
    RataTieto rata1 = new RataTieto(0, "rata1" , koePar); 
    int[] koePar2 = { 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3} ; 
    RataTieto rata2 = new RataTieto(0, "rata2", koePar2); 
    int[] koePar3 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1} ; 
    RataTieto rata3 = new RataTieto(0, "rata3", koePar3); 
    hakukoe.lisaaRata(rata1); 
    hakukoe.lisaaRata(rata2); 
    hakukoe.lisaaRata(rata3); 
    List<RataTieto> hk = hakukoe.etsiRadat("eka"); 
    assertEquals("From: Rata line: 234", 0, hk.size()); 
    hk = hakukoe.etsiRadat("ta"); 
    assertEquals("From: Rata line: 236", 3, hk.size()); 
    hk = hakukoe.etsiRadat("rata3"); 
    assertEquals("From: Rata line: 238", 1, hk.size()); 
    assertEquals("From: Rata line: 239", "3|rata3|1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1", hk.get(0).toString()); 
    hk = hakukoe.etsiRadat(""); 
    assertEquals("From: Rata line: 241", 3, hk.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKorvaaTaiLisaa282 */
  @Test
  public void testKorvaaTaiLisaa282() {    // Rata: 282
    Rata koe = new Rata(1); 
    int[] koePar = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} ; 
    RataTieto rata1 = new RataTieto(1, "rata1" , koePar); 
    int[] koePar2 = { 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3} ; 
    RataTieto rata2 = new RataTieto(2, "rata2", koePar2); 
    int[] koePar3 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1} ; 
    RataTieto rata3 = new RataTieto(1, "rata3", koePar3); 
    assertEquals("From: Rata line: 292", false, koe.korvaaTaiLisaa(rata1)); 
    assertEquals("From: Rata line: 293", false, koe.korvaaTaiLisaa(rata2)); 
    assertEquals("From: Rata line: 294", 2, koe.annaRataMaara()); 
    assertEquals("From: Rata line: 295", "1|rata1|1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18", koe.kasaaRata(1).toString()); 
    assertEquals("From: Rata line: 296", "2|rata2|3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3", koe.kasaaRata(2).toString()); 
    assertEquals("From: Rata line: 297", true, koe.korvaaTaiLisaa(rata3)); 
    assertEquals("From: Rata line: 298", 2, koe.annaRataMaara()); 
    assertEquals("From: Rata line: 299", "1|rata3|1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1", koe.kasaaRata(1).toString()); 
  } // Generated by ComTest END
}