package tuloskortti.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.01 15:51:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RataTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi45 */
  @Test
  public void testRekisteroi45() {    // Rata: 45
    Rata koe = new Rata(1); 
    assertEquals("From: Rata line: 47", 0, koe.getId()); 
    koe.rekisteroi(); 
    assertEquals("From: Rata line: 49", 1, koe.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaRata63 */
  @Test
  public void testLisaaRata63() {    // Rata: 63
    Rata lisakoe = new Rata(1); 
    lisakoe.perusRata(); 
    String[] em = { "Esimerkki", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18"} ; 
    lisakoe.lisaaRata(em); 
    String[] uusirata = { "Toppila", "3", "3", "3", "3", "3", "3", "3", "3", "3", "4", "3", "3", "3", "3", "3", "3", "3", "3"} ; 
    lisakoe.lisaaRata(uusirata); 
    String[] uusirata2 = { "Virpiniemi", "3", "3", "4", "5", "4", "3", "3", "3", "3", "4", "3", "3", "3", "6", "3", "3", "3", "3"} ; 
    lisakoe.lisaaRata(uusirata2); 
    assertEquals("From: Rata line: 73", 4, lisakoe.annaRataMaara()); 
    assertEquals("From: Rata line: 74", 4, lisakoe.getId());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKasaaRata101 */
  @Test
  public void testKasaaRata101() {    // Rata: 101
    Rata kasakoe = new Rata(1); 
    kasakoe.perusRata(); 
    String[] ok = kasakoe.kasaaRata(1); 
    assertEquals("From: Rata line: 106", "[PerusNimi, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]", Arrays.toString(ok)); 
    ok = kasakoe.kasaaRata(2); 
    assertEquals("From: Rata line: 108", "[, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]", Arrays.toString(ok)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaRataMaara132 */
  @Test
  public void testAnnaRataMaara132() {    // Rata: 132
    Rata koe = new Rata(1); 
    assertEquals("From: Rata line: 134", 0, koe.annaRataMaara()); 
    koe.perusRata(); 
    assertEquals("From: Rata line: 136", 1, koe.annaRataMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetId163 */
  @Test
  public void testGetId163() {    // Rata: 163
    Rata koe = new Rata(1); 
    assertEquals("From: Rata line: 165", 0, koe.getId()); 
    koe.rekisteroi(); 
    assertEquals("From: Rata line: 167", 1, koe.getId()); 
    koe.perusRata(); 
    assertEquals("From: Rata line: 169", 2, koe.getId()); 
  } // Generated by ComTest END
}