package tuloskortti.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.22 14:48:56 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RataTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi46 */
  @Test
  public void testRekisteroi46() {    // Rata: 46
    Rata koe = new Rata(1); 
    assertEquals("From: Rata line: 48", 0, koe.uusinId()); 
    koe.rekisteroi(); 
    assertEquals("From: Rata line: 50", 1, koe.uusinId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaaRata64 */
  @Test
  public void testLisaaRata64() {    // Rata: 64
    Rata lisakoe = new Rata(1); 
    int[] koePar = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} ; 
    RataTieto rata1 = new RataTieto(1, "rata1" , koePar); 
    int[] koePar2 = { 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3} ; 
    RataTieto rata2 = new RataTieto(2, "rata2", koePar2); 
    int[] koePar3 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1} ; 
    RataTieto rata3 = new RataTieto(1, "rata3", koePar3); 
    lisakoe.lisaaRata(rata1); 
    assertEquals("From: Rata line: 75", 1, lisakoe.annaRataMaara()); 
    lisakoe.lisaaRata(rata2); 
    lisakoe.lisaaRata(rata3); 
    assertEquals("From: Rata line: 78", 3, lisakoe.annaRataMaara()); 
    assertEquals("From: Rata line: 79", 3, lisakoe.uusinId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaRataMaara149 */
  @Test
  public void testAnnaRataMaara149() {    // Rata: 149
    Rata koe = new Rata(1); 
    assertEquals("From: Rata line: 151", 0, koe.annaRataMaara()); 
    koe.perusRata(); 
    assertEquals("From: Rata line: 153", 1, koe.annaRataMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testUusinId165 */
  @Test
  public void testUusinId165() {    // Rata: 165
    Rata koe = new Rata(1); 
    assertEquals("From: Rata line: 167", 0, koe.uusinId()); 
    koe.rekisteroi(); 
    assertEquals("From: Rata line: 169", 1, koe.uusinId()); 
    koe.perusRata(); 
    assertEquals("From: Rata line: 171", 2, koe.uusinId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsiRadat183 */
  @Test
  public void testEtsiRadat183() {    // Rata: 183
    Rata hakukoe = new Rata(1); 
    int[] koePar = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} ; 
    RataTieto rata1 = new RataTieto(0, "rata1" , koePar); 
    int[] koePar2 = { 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3} ; 
    RataTieto rata2 = new RataTieto(0, "rata2", koePar2); 
    int[] koePar3 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1} ; 
    RataTieto rata3 = new RataTieto(0, "rata3", koePar3); 
    hakukoe.lisaaRata(rata1); 
    hakukoe.lisaaRata(rata2); 
    hakukoe.lisaaRata(rata3); 
    List<RataTieto> hk = hakukoe.etsiRadat("eka"); 
    assertEquals("From: Rata line: 197", 0, hk.size()); 
    hk = hakukoe.etsiRadat("ta"); 
    assertEquals("From: Rata line: 199", 3, hk.size()); 
    hk = hakukoe.etsiRadat("rata3"); 
    assertEquals("From: Rata line: 201", 1, hk.size()); 
    assertEquals("From: Rata line: 202", "3|rata3|1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7, 6, 5, 4, 3, 2, 1", hk.get(0).toString()); 
    hk = hakukoe.etsiRadat(""); 
    assertEquals("From: Rata line: 204", 3, hk.size()); 
  } // Generated by ComTest END
}