package tuloskortti.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import static tuloskortti.Tuloskortti.*;
import tuloskortti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.31 16:17:18 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuloskorttiTest {



  // Generated by ComTest BEGIN
  /** testPatki24 */
  @Test
  public void testPatki24() {    // Tuloskortti: 24
    String[] koe = patki("15        | testi "); 
    assertEquals("From: Tuloskortti line: 26", "15", koe[0]); 
    assertEquals("From: Tuloskortti line: 27", "testi", koe[1]); 
    String[] koe2 = patki(" 150 \n | \n rivivaihto             "); 
    assertEquals("From: Tuloskortti line: 29", "150", koe2[0]); 
    assertEquals("From: Tuloskortti line: 30", "rivivaihto", koe2[1]); 
    String[] koe3 = patki("|"); 
    assertEquals("From: Tuloskortti line: 32", "", koe3[0]); 
    assertEquals("From: Tuloskortti line: 33", "", koe3[1]); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaRata65 */
  @Test
  public void testAnnaRata65() {    // Tuloskortti: 65
    Tuloskortti tkoe = new Tuloskortti(1); 
    tkoe.lisaaPerus(); 
    String[] ok = tkoe.annaRata(1); 
    assertEquals("From: Tuloskortti line: 70", "[PerusNimi, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]", Arrays.toString(ok));
    ok = tkoe.annaRata(2); 
    assertEquals("From: Tuloskortti line: 72", "[, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]", Arrays.toString(ok)); 
  } // Generated by ComTest END
}